Final version v2
ardium-pl/Inwentaryzacja-ng pull request #7
Opened 2024-07-11 19:02 UTC by Floressek

Proba merge z mainem v2

2024-07-15 12:23 UTC, joker876 requested changes

2024-07-15 12:23 UTC, joker876 commented on src/index.html
> +  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
Importy styli przenieść do `styles.scss` (z użyciem `@import`)

2024-07-15 12:26 UTC, joker876 commented on src/app/transactions/transactions.component.ts
> +  defaultValues: DefaultValuesService = inject(DefaultValuesService);
Nie ma potrzeby definiowania typu tego pola. Wiadomo, że injectujemy konkretną klasę, więc definiowanie osobno typu zmiennej jest nadmiarowe.

2024-07-15 12:26 UTC, joker876 commented on src/app/transactions/transactions.component.ts
> +  defaultValues: DefaultValuesService = inject(DefaultValuesService);
Poza tym wszystkie pola, w których używane jest `inject` powinny być oznaczone jako `readonly`

2024-07-15 12:28 UTC, joker876 commented on src/app/transactions/transactions.component.ts
> +  ];
Te wszystkie definikcje kolumn najlepiej przenieść do osobnego pliku, żeby nie zaśmiecały komponentu. Można stworzyć np. plik `col-defs.ts` i tam zdefiniować to jako zwykłe zmienne.

2024-07-15 12:31 UTC, joker876 commented on src/app/transactions/transactions.component.ts
> +  }
Sygnały typu `computed` definiuje się bezpośrednio w polu, nie trzeba używać do tego konstruktora. I wszelkie pola z sygnałami powinny zawsze być `readonly`.
```ts
readonly transaction = computed<Transaction[]>(() => { /* kod funkcji */ });

2024-07-15 12:33 UTC, joker876 commented on src/app/transactions/transactions.component.ts
> +  @Input() permanentTab!: string;
Zamiast `@Input()` używamy w naszych aplikacjach sygnału `input`.

```ts
readonly companyName = input<string>('');
// lub aby input był wymagany do wypełnienia
readonly companyName = input.required<string>();
```

2024-07-15 12:39 UTC, joker876 commented on src/app/transactions/transactions.component.ts
> +  suppressScrollOnNewData: boolean = true;
Wszystkie te pola powinny być zamienione na sygnały z użyciem `signal<typ>(wartość początkowa)`

2024-07-15 12:43 UTC, joker876 commented on src/app/transactions/transactions.component.html
> +-->
Takie komentarze nie są zbyt pomocne w kodzie. Warto sobie przeczytać [ten artykuł](https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/) na Stack Overflow (w tym przypadku szczególnie punkt zasada 1)

2024-07-15 12:43 UTC, joker876 commented on src/app/transactions/transactions.component.css
> + */
Do usunięcia

2024-07-15 12:43 UTC, joker876 commented on src/app/transactions/transactions.component.css
> + */
Do usunięcia

2024-07-15 12:47 UTC, joker876 commented on src/app/transaction.ts
> + */
Ten komentarz duplikuje komentarze liniowe wewnątrz samego interfejsu. Albo usunąć ten komentarz, albo komentarze liniowe.

A najlepiej jakby opisać każde pole z osobna:
```ts
interface Transaction {
    // inne pola
    /**
     * CIT art. 11n exemption.
     */
    taxExemption: string;
    // inne pola
}

2024-07-15 12:47 UTC, joker876 commented on src/app/transaction-data-storage.service.ts
> +  defaultValues: DefaultValuesService = inject(DefaultValuesService);
`readonly` i usunąć typ

2024-07-15 12:48 UTC, joker876 commented on src/app/transaction-data-storage.service.ts
> +  transactions = signal<Transaction[]>([]);
readonly

2024-07-15 12:48 UTC, joker876 commented on src/app/transaction-data-storage.service.ts
> +  ]);
readonly

2024-07-15 12:52 UTC, joker876 commented on src/app/transaction-data-storage.service.ts
> +  ]);
I jako że to jest wartość stała, która nigdy ma się nie zmieniać to zasygnalizować to zapisująć w `CONSTANT_CASE` zamiast w `camelCase`. W rezultacie będzie: `LIMITS`.

2024-07-15 12:52 UTC, joker876 commented on src/app/transaction-data-storage.service.ts
> +  inna_limit: number = 2000000;
`readonly` i zapisać jako `CONSTANT_CASE` (czyli w tym przypadku `INNA_LIMIT`).

2024-07-15 12:55 UTC, joker876 commented on src/app/tab-content/tab-content.component.ts
> + */
Do usunięcia

2024-07-15 12:57 UTC, joker876 commented on src/app/navbar/navbar.component.ts
> + */
Do usunięcia.

2024-07-15 12:57 UTC, joker876 commented on src/app/navbar/navbar.component.html
> +-->
Do usunięcia

2024-07-15 12:57 UTC, joker876 commented on src/app/material-tabs-test/material-tabs-test.component.ts
> +   */
Do usunięcia

2024-07-15 12:58 UTC, joker876 commented on src/app/material-tabs-test/material-tabs-test.component.ts
> +  uniqueCompanies = computed(() => {
readonly

2024-07-15 12:59 UTC, joker876 commented on src/app/material-tabs-test/material-tabs-test.component.ts
> +  }
To samo co w którymś z powyższym komentarzy. `computed` definiuje się bezpośrednio w polu, nie w konstruktorze.

2024-07-15 13:00 UTC, joker876 commented on src/app/material-tabs-test/material-tabs-test.component.ts
> + */
Do usunięcia

2024-07-15 13:06 UTC, joker876 commented on src/app/input-page/input-page.component.ts
> +  manualAnalysisRequired: boolean = false;
Przerobić na sygnały

2024-07-15 13:07 UTC, joker876 commented on src/app/input-page/input-page.component.ts
> +  router: Router = inject(Router);
Usunąć typy

2024-07-15 13:07 UTC, joker876 commented on src/app/input-page/input-page.component.html
> +</div>
Pousuwać komentarze

2024-07-15 13:08 UTC, joker876 commented on src/app/default-values.service.ts
> +  noContentAfterEdit: number = 0; // Replaces null
Przerobić na sygnały

2024-07-15 13:12 UTC, joker876 commented on src/app/company.ts
> + **/
Ten komentarz cały też najlepiej rozbić na komentarze do pojedynczych pól tak jak gdzieś wyżej.

2024-07-15 13:14 UTC, joker876 commented on src/app/company-data-storage.service.ts
> +  );
Usunąć typ

2024-07-15 13:14 UTC, joker876 commented on src/app/company-data-storage.service.ts
> +  transactions: Signal<Transaction[]>;
Zdefiniować `computed` bezpośrednio w polu

2024-07-15 13:15 UTC, joker876 commented on src/app/color-toggle/color-toggle.component.ts
> +  @Output() clearColors = new EventEmitter<void>();
Zamiast `@Ouptut` użyć `readonly clearColors = ouptut<void>();`

2024-07-15 13:20 UTC, joker876 commented on src/app/app.routes.ts
> + */
Do usunięcia

2024-07-15 13:20 UTC, joker876 commented on src/app/app.config.ts
> + */
Do usunięcia

2024-07-15 13:24 UTC, joker876 commented on src/app/analiza-zwolnien/analiza-zwolnien.component.ts
> +  ];
Prznieść do osobnego pliku `.ts` żeby nie zaśmiecało komponentu

2024-07-15 13:25 UTC, joker876 commented on src/app/analiza-zwolnien/analiza-zwolnien.component.ts
> +  };
To też przenieść do osobnego pliku razem z resztą definicji.

2024-07-15 13:26 UTC, joker876 commented on src/app/analiza-zwolnien/analiza-zwolnien.component.ts
> +  }
Tu też ta sama sprawa z `computed`

2024-07-15 13:26 UTC, joker876 commented on src/app/analiza-zwolnien/analiza-zwolnien.component.ts
> +  defaultValues: DefaultValuesService = inject(DefaultValuesService);
usunąć typy

2024-07-15 13:28 UTC, joker876 commented on src/app/material-tabs-test/material-tabs-test.component.ts
> +  permanentTabName2: string = 'Obowiązki CT';
Nie wiem czy te wartości są stałe czy zmienne, więc jeśli zmienne to przerobić na sygnały, a jeśli stałe to zmienić na `CONSTANT_CASE`. I w obu przypadkach dać `readonly`

2024-07-15 13:29 UTC, joker876 commented
Usunąć wszystkie pliki `.spec.ts`. To są pliki do testów automatycznych, a ich na ten moment nie będziemy stosować.

2024-07-15 13:31 UTC, joker876 commented
Znajdowałem w kodzie bardzo dużo komentarzy, które niewiele wnosiły do kodu (a wręcz bardziej zajmowały przestrzeń). Wszystkie takie komentarze proszę pousuwać. Jeśli uważacie, że jakiś komentarz powinien zostać, to zostawcie, tylko upewnijcie się że jest zgodny z zasadami opisanymi w artykule: https://stackoverflow.blog/2021/12/23/best-practices-for-writing-code-comments/

2024-07-15 13:32 UTC, joker876 commented
I ważna informacja na koniec: Za każdym razem jak rozwiążecie jakiś problem, któy wam zgłosiłem to oznaczcie go jako "resolved"
![image](https://github.com/user-attachments/assets/674841fa-68b1-4b22-886c-3b459c64f546)

2024-07-15 13:36 UTC, Floressek commented on angular.json
> +      "schematics": {},
"projects": {
    "Inwentaryzacja-ng": {
      "projectType": "application",
      "schematics": {
        "@schematics/angular:component": {
          "skipTests": true,
          "style": "scss"
        },
        "@schematics/angular:directive": {
          "skipTests": true
        },
        "@schematics/angular:pipe": {
          "skipTests": true
        },
        "@schematics/angular:guard": {
          "skipTests": true
        },
        "@schematics/angular:service": {
          "skipTests": true
        }
        done

2024-07-15 16:01 UTC, Floressek commented on src/app/company.ts
> + **/
gdzieś wyżej?

2024-07-17 13:51 UTC, closed without merging

2024-07-17 13:51 UTC, Floressek commented
new pull request to be created -> final version